### ISSUE TITLE
Fix - Loading

### ISSUE THREAD

**Issue by pizelli** [Fernanda-Kipper/landing-page-ssr#1]
No arquivo: **src/app/components/newsletter-form/newsletter-form.component.ts**
Coloque no **subscribe**: error: () => this.loading.set(false) 
Para caso retorne algum erro o **loading** não permaneça na tela.

**Comment by Fernanda-Kipper** [comment]
Boa, gostei da sugestão!! 
Consegue abrir uma PR com essa solução?

**Comment by pizelli** [comment]
Done!
